name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # example: [examples/Bluetooth/PS3SPP/PS3SPP.ino, examples/pl2303/pl2303_gps/pl2303_gps.ino]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Download external library
        run: |
          wget https://github.com/carrino/Quaternion/archive/master.zip -O /tmp/Quaternion.zip
          wget https://github.com/sparkfun/SparkFun_BMP581_Arduino_Library/archive/master.zip -O /tmp/SparkFun_BMP581_Arduino_Library.zip
          wget https://github.com/sparkfun/SparkFun_MMC5983MA_Magnetometer_Arduino_Library/archive/master.zip -O /tmp/SparkFun_MMC5983MA_Magnetometer_Arduino_Library.zip 
          wget https://github.com/bolderflight/bmi088-arduino/archive/master.zip -O /tmp/bmi088-arduino.zip
          wget https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/archive/master.zip -O /tmp/SparkFun_u-blox_GNSS_Arduino_Library
          wget https://github.com/shivammpat/MadgwickAHRS/archive/master.zip -O /tmp/MadgwickAHRS.zip
          wget https://github.com/tomstewart89/BasicLinearAlgebra/archive/master.zip -O /tmp/BasicLinearAlgebra.zip
          unzip "/tmp/*.zip" -d /tmp

      - name: Run PlatformIO
        run: pio ci --lib="." --lib="/tmp/*" --board=teensy41
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}
